import { useState } from 'react';
import type { Priority, Task } from '../types/database';

export type NewTaskInput = Pick<Task, 'name' | 'project_id' | 'in_focus' | 'focus_note' | 'estimated_minutes' | 'priority'>;
/** Reusable new-task dialog. Pass an API route-backed estimator so provider keys stay server-side. */
export function TaskModal({ projectId, projectContext, onCreate, estimate }: { projectId: string; projectContext: string; onCreate: (input: NewTaskInput) => Promise<void>; estimate?: (name: string, context: string) => Promise<number> }) {
  const [name, setName] = useState(''); const [focus, setFocus] = useState(false); const [minutes, setMinutes] = useState<number | ''>(''); const [saving, setSaving] = useState(false);
  return <form className="glass-panel space-y-4 p-5" onSubmit={async e => { e.preventDefault(); if (!name.trim()) return; setSaving(true); try { const estimated_minutes = minutes === '' && estimate ? await estimate(name, projectContext) : (minutes || null); await onCreate({ name: name.trim(), project_id: projectId, in_focus: focus, focus_note: null, priority: 3 as Priority, estimated_minutes }); } finally { setSaving(false); } }}><h2 className="text-lg font-semibold">New task</h2><input required value={name} onChange={e => setName(e.target.value)} placeholder="Task name" className="w-full rounded-lg border border-white/15 bg-white/5 p-2 outline-none" /><label className="flex items-center justify-between text-sm">Add to Focus Board <button type="button" onClick={() => setFocus(!focus)} aria-pressed={focus} className={focus ? 'text-amber-300' : 'text-slate-500'}>{focus ? '★ In focus' : '☆ Add focus'}</button></label><label className="block text-sm">Estimate (minutes; leave blank for AI)<input type="number" min="15" max="480" step="15" value={minutes} onChange={e => setMinutes(e.target.value ? Number(e.target.value) : '')} className="mt-1 block w-full rounded-lg border border-white/15 bg-white/5 p-2" /></label><button disabled={saving} className="rounded-lg bg-indigo-500 px-4 py-2 text-sm disabled:opacity-50">{saving && minutes === '' ? 'Estimating…' : 'Create task'}</button></form>;
}
