import { StrictMode, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { FocusBoard } from './components/FocusBoard';
import { PaymoControl } from './components/PaymoControl';
import { supabase } from './lib/supabase';
import type { Client, FocusTask, Project, Task } from './types/database';
import './styles.css';

type Page = 'focus' | 'tasks' | 'projects' | 'clients';
const now = () => new Date().toISOString(); const uid = () => crypto.randomUUID();
const client = (name: string): Client => ({ id: uid(), user_id: 'local', name, paymo_id: null, created_at: now(), updated_at: now() });
const project = (name: string, client_id: string): Project => ({ id: uid(), user_id: 'local', name, client_id, status: 'Active', paymo_id: null, created_at: now(), updated_at: now() });
function App() {
  const [page, setPage] = useState<Page>('focus'); const [clients, setClients] = useState<Client[]>([]); const [projects, setProjects] = useState<Project[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [dialog, setDialog] = useState<'client'|'project'|'task'|null>(null); const [syncNote, setSyncNote] = useState('');
  useEffect(() => { const raw = localStorage.getItem('taskboard'); if (raw) { const d = JSON.parse(raw); setClients(d.clients); setProjects(d.projects); setTasks(d.tasks); } else { const c = client('Acme Studio'), p = project('Website refresh', c.id); setClients([c]); setProjects([p]); setTasks([{ id: uid(), user_id: 'local', project_id: p.id, name: 'Prepare launch brief', status: 'To Do', assignee: null, due_date: null, notes: null, priority: 1, in_focus: true, focus_note: 'Make the decision crisp.', estimated_minutes: 60, logged_minutes: 0, time_block: 'Morning', paymo_id: null, created_at: now(), updated_at: now() }]); } }, []);
  useEffect(() => { if (clients.length) localStorage.setItem('taskboard', JSON.stringify({ clients, projects, tasks })); }, [clients, projects, tasks]);
  const focusTasks: FocusTask[] = useMemo(() => tasks.map(t => { const p = projects.find(x => x.id === t.project_id); const c = clients.find(x => x.id === p?.client_id); return { ...t, project: { id: p?.id ?? '', name: p?.name ?? 'Unassigned', status: p?.status ?? 'Archived', client: { id: c?.id ?? '', name: c?.name ?? 'Unknown' } } }; }), [tasks, projects, clients]);
  const updateTask = async (id: string, patch: Partial<Task>) => setTasks(xs => xs.map(t => t.id === id ? { ...t, ...patch, updated_at: now() } : t));
  const loadCloudData = async () => { if (!supabase) return; const [{ data: cloudClients, error: clientError }, { data: cloudProjects, error: projectError }, { data: cloudTasks, error: taskError }] = await Promise.all([supabase.from('clients').select('*').order('name'), supabase.from('projects').select('*').eq('status', 'Active').order('name'), supabase.from('tasks').select('*').not('status', 'in', '(Done,Archived)').order('created_at')]); if (clientError || projectError || taskError) { setSyncNote(clientError?.message ?? projectError?.message ?? taskError?.message ?? 'Could not load synced data.'); return; } setClients(cloudClients as Client[]); setProjects(cloudProjects as Project[]); setTasks(cloudTasks as Task[]); };
  const addClient = (name: string) => setClients(xs => [...xs, client(name)]); const addProject = (name: string, clientId: string) => setProjects(xs => [...xs, project(name, clientId)]); const addTask = (name: string, projectId: string, focus: boolean) => setTasks(xs => [...xs, { id: uid(), user_id: 'local', project_id: projectId, name, status: 'To Do', assignee: null, due_date: null, notes: null, priority: 3, in_focus: focus, focus_note: null, estimated_minutes: null, logged_minutes: 0, time_block: null, paymo_id: null, created_at: now(), updated_at: now() }]);
  return <main className="ambient-bg flex min-h-screen"><aside className="m-3 hidden w-60 shrink-0 flex-col rounded-2xl border border-white/10 bg-slate-950/25 p-3 backdrop-blur-md md:flex"><b className="mb-8 px-2 text-xl">Taskboard</b>{([['focus','◉ Focus Board'],['tasks','✓ All Tasks'],['projects','▣ Projects'],['clients','◌ Clients']] as [Page,string][]).map(([key,label]) => <button key={key} onClick={() => setPage(key)} className={`mb-1 rounded-lg px-3 py-2 text-left text-sm ${page === key ? 'bg-white/12' : 'text-slate-300 hover:bg-white/5'}`}>{label}</button>)}<button onClick={() => setDialog('client')} className="mt-auto rounded-lg p-2 text-left text-sm text-slate-300 hover:bg-white/5">+ New client</button></aside><section className="min-w-0 flex-1 p-5 lg:p-8"><header className="mb-7 flex flex-wrap justify-between gap-3"><div><p className="text-sm text-indigo-200">Workspace</p><h1 className="text-3xl font-semibold">{page === 'focus' ? 'Focus Board' : page === 'tasks' ? 'All Tasks' : page[0].toUpperCase() + page.slice(1)}</h1></div><div className="flex flex-wrap items-center gap-2"><PaymoControl onSynced={async result => { await loadCloudData(); setSyncNote(`Paymo: ${result.clients} active clients, ${result.projects} active projects, ${result.tasks} open tasks synced.`); }} /><button onClick={() => setDialog(page === 'clients' ? 'client' : page === 'projects' ? 'project' : 'task')} className="rounded-lg bg-indigo-500 px-3 py-2 text-sm">+ New {page === 'clients' ? 'client' : page === 'projects' ? 'project' : 'task'}</button></div></header>{syncNote && <p className="mb-4 rounded-lg bg-amber-400/15 p-3 text-sm text-amber-100">{syncNote}</p>}{page === 'focus' && <FocusBoard tasks={focusTasks} updateTask={updateTask} />}{page === 'tasks' && <TaskList tasks={focusTasks} updateTask={updateTask} />}{page === 'projects' && <Cards items={projects.filter(p => p.status === 'Active').map(p => ({ title: p.name, detail: `${clients.find(c => c.id === p.client_id)?.name ?? 'No client'} · ${tasks.filter(t => t.project_id === p.id).length} tasks` }))} />}{page === 'clients' && <Cards items={clients.filter(c => projects.some(p => p.client_id === c.id && p.status === 'Active')).map(c => ({ title: c.name, detail: `${projects.filter(p => p.client_id === c.id && p.status === 'Active').length} active projects` }))} />}{dialog && <Create type={dialog} clients={clients} projects={projects} addClient={addClient} addProject={addProject} addTask={addTask} close={() => setDialog(null)} />}</section></main>;
}
function Cards({ items }: { items: {title:string;detail:string}[] }) { return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map(x => <article key={x.title} className="glass-card p-4"><h2 className="font-medium">{x.title}</h2><p className="mt-2 text-sm text-slate-400">{x.detail}</p></article>)}</div>; }
function TaskList({ tasks, updateTask }: {tasks: FocusTask[]; updateTask:(id:string,p:Partial<Task>)=>Promise<void>}) { return <div className="glass-panel overflow-auto"><table className="w-full min-w-150 text-left text-sm"><thead className="border-b border-white/10 text-slate-400"><tr><th className="p-3">Task</th><th>Project</th><th>Status</th><th>Focus</th></tr></thead><tbody>{tasks.map(t => <tr className="border-b border-white/5" key={t.id}><td className="p-3">{t.name}</td><td>{t.project.name}</td><td>{t.status}</td><td><button onClick={() => void updateTask(t.id,{in_focus:!t.in_focus})} className={t.in_focus?'text-amber-300':'text-slate-500'}>{t.in_focus?'★':'☆'}</button></td></tr>)}</tbody></table></div>; }
function Create({ type, clients, projects, addClient, addProject, addTask, close }: {type:'client'|'project'|'task';clients:Client[];projects:Project[];addClient:(s:string)=>void;addProject:(s:string,c:string)=>void;addTask:(s:string,p:string,f:boolean)=>void;close:()=>void}) { const [name,setName]=useState(''); const [target,setTarget]=useState(type==='project'?clients[0]?.id??'':projects[0]?.id??''); const [focus,setFocus]=useState(false); return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/65 p-4"><form className="glass-panel w-full max-w-md space-y-4 p-5" onSubmit={e=>{e.preventDefault();if(!name.trim())return;if(type==='client')addClient(name);if(type==='project')addProject(name,target);if(type==='task')addTask(name,target,focus);close();}}><div className="flex justify-between"><h2 className="text-lg font-semibold">New {type}</h2><button type="button" onClick={close}>×</button></div><input autoFocus required value={name} onChange={e=>setName(e.target.value)} placeholder={`${type} name`} className="w-full rounded-lg border border-white/15 bg-white/5 p-2.5" />{type!=='client'&&<select value={target} onChange={e=>setTarget(e.target.value)} className="w-full rounded-lg border border-white/15 bg-slate-900 p-2.5">{(type==='project'?clients:projects).map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select>}{type==='task'&&<label className="flex gap-2 text-sm"><input type="checkbox" checked={focus} onChange={e=>setFocus(e.target.checked)}/>Add to Focus Board</label>}<button className="rounded-lg bg-indigo-500 px-4 py-2 text-sm">Create</button></form></div>; }
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);
